application: televisionnotifier 
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /javascript
  static_dir: javascript
- url: /
  script: listchannels.py
- url: /confirmchannels
  script: listchannels.py
- url: /searchshow
  script: listchannels.py
- url: /setupemailalert
  script: listchannels.py
- url: /check
  script: check.py
