application: televisionnotifier 
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /javascript
  static_dir: javascript
- url: /channels
  script: selectchannels.py
- url: /series
  script: selectseries.py
- url: /show
  script: showresults.py
- url: /setupemail
  script: setemailalert.py
- url: /check
  script: check.py
- url: /cron/channels
  script: getchannelslist.py
- url: /cron/schedule
  script: geteachschedule.py
